config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'posts#index'
  resources :posts do
    resources :comments, only: [:new, :create, :delete]
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
      get "top", to: "post#top"
    end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :artists do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/views/pages/_home.html.erb
<div class="row">
	<div class="col-lg-12">
    <div class="intro-message">
	    <h1>Landing Page</h1>
	    <h3>Template for Landing Page</h3>
	    <hr class="intro-divider">
	    <ul class="list-inline intro-social-buttons">
	        <li>
	            <i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span>
	        </li>
	        <li>
	            <i class="fa fa-instagram fa-fw"></i> <span class="network-name">Instgram</span>
	        </li>
	        <li>
	        	<%= link_to  "Artist Signup", new_artist_path, class: "network-name btn btn-info" %>
	        </li>
	    </ul>
	</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Inkly!</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>
</div>

app/views/pages/yelp.html.erb
<div id="map_canvas">
	<div id="control_container">
		<div id="map_search">
			<form input type="text">
				<a href="#" id="map_search_submit"><i class="fa fa-search"></i></a>
			</form>
		</div>
		<div id="results">
			
		</div>
	</div>
</div>