config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'posts#index'
  resources :posts do
    resources :comments, only: [:new, :create, :delete]
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
      get "top", to: "post#top"
    end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :artists do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	acts_as_votable
	has_attached_file :image, :styles => { :medium => "500x500", :thumb => "100x100" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	validates_presence_of :image


#need to add size validations
# validates_attachment :avatar, :presence => true,
#   :content_type => { :content_type => "image/jpeg" },
#   :size => { :in => 0..10.kilobytes }

	def score
		self.get_upvotes.size - self.get_downvotes.size
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 10)
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.all
		@comment = @post.comments.build
	end

	def new
		@post = current_user.posts.build
	end

	def edit
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Created new post!"
			redirect_to @post
		else
			render action: "new"
		end
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Updated Post"
			redirect_to @posts
		else
			render action: "edit"
		end
	end

	def destroy
		@post.destroy
		flash[:danger] = "Post Deleted"
		redirect_to posts_path
	end

	def upvote
		@post.upvote_by current_user
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end

	end

	def downvote
		@post.downvote_by current_user
		respond_to do |format|
			format.html { redirect_to root_path }
			format.js
		end
	end

	def top
		@posts = Post.all.score.order("DESC").paginate(page: params[:page], per_page: 10)
	end

	private

		def set_post
			@post = Post.find(params[:id])
		end

		def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
    end

		def post_params
			params.require(:post).permit(:description, :image)
		end
		
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

app/views/posts/_lightbox.html.erb
<div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
  <!-- The container for the modal slides -->
  <div class="slides"></div>
  <!-- Controls for the borderless lightbox -->
 <!--  <h3 class="title"></h3>
  <a class="prev">‹</a>
  <a class="next">›</a> -->
  <a class="close">×</a>
  <!-- The modal dialog, which will be used to wrap the lightbox content -->
  <div class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Post Description</h4>
        </div>
        <div class="modal-body next"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left prev">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Previous
          </button>
          <button type="button" class="btn btn-primary next">
            Next
            <i class="glyphicon glyphicon-chevron-right"></i>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
<% if @post.new_record? %>
  alert('Failed');
<% else %>
  $('ul.thumbnails').append("<%=j render partial: 'photosets/upload', locals: { upload: @upload } %>");
<% end %>

app/views/posts/downvote.js.erb
$("#post-<%= @post.id %>-score	").html('<%= @post.score %>');

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "pages/home" unless user_signed_in? %>

<div id="posts" class="transitions-enabled modal-gallery">
  <% @posts.each do |post| %>
    <div class="box panel panel-default">
      <a href="<%= post.image.url %>" data-gallery>
        <%= image_tag(post.image.url) %>
      </a>
      <%= render "lightbox" %>
      <div class="panel-body">
        <%= post.description %><br/>
        <strong><%=link_to post.user.name, artist_path(post.user.profile_id) if post.user %></strong>
        <p><%= link_to "Comments", post_path(post) %></p>
        <% if current_user && post.user == current_user %>
          <div class="actions"> 
            <%= link_to edit_post_path(post)  do %>
              <i class="fa fa-pencil-square-o"></i> Edit
            <% end %>
            <%= link_to post, method: :delete, data: { confirm: "Are you sure?" }  do %>
              <i class="fa fa-trash-o"></i> Delete
            <% end %>
            </div>
        <% end %>
      </div>
      <div class="panel-footer center">
        <% if user_signed_in? %>
         <%= link_to upvote_post_path(post), remote: true, method: :put do %>
            <i class="fa fa-caret-square-o-up fa-2x"></i>
          <% end %>
          <%= link_to downvote_post_path(post), remote: true, method: :put do %>
            <i class="fa fa-caret-square-o-down fa-2x"></i>
          <% end %>
        <% end %>
        <div id="post-<%= post.id %>-score" class="post-score">
          <%= post.score %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="center">
  <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @post.image.url %>
			</div>
			<div class="panel-body">
				<p><%= @post.description %></p>
				<p><strong><%= link_to @post.user.name, artist_path(@post.user.profile_id) if @post.user  %></strong></p>
				<% if @post.user == current_user %>
					<%= link_to edit_post_path(@post)  do %>
            <i class="fa fa-pencil-square-o"></i> Edit
          <% end %>
          <%= link_to @post, method: :delete, data: { confirm: "Are you sure?" }  do%>
            <span class="fa fa-trash-o"></span> Delete
          <% end %>
				<% end %>
			</div>
		</div>
		<%= link_to 'Back', posts_path %>
	</div>
</div>
<div class="row">
		<h3>Comments</h3>
			<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user.name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>
</div>

app/views/posts/upvote.js.erb
$("#post-<%= @post.id %>-score	").html('<%= @post.score %>');