config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'posts#index'
  resources :posts do
    resources :comments, only: [:new, :create, :delete]
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
      get "top", to: "post#top"
    end
  end

  devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :artists do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Squidly", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
         <li>
            <%= link_to new_post_path do %>
              <i class="fa fa-plus-square-o"></i>New Post
            <% end %>
          </li>
          <li>
            <%= link_to artists_path do %>
              <i class="fa fa-anchor"></i>Artists
            <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bolt"></i>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
              <% if artist? %>
                <li><%= link_to "My Profile", artist_path(current_user.profile_id) %></li>
              <% else %>
                <li><%= link_to "My Profile", user_path(current_user.id) %></li>
              <% end %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TattooSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>
	<%= render "layouts/header" %>
	<div class="container">
		<% flash.each do |type, message| %>
		  <div class="alert alert-<%= type %> alert-dismissable">
		    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		    <%= message %>
		  </div>
		<% end %>
		<%= yield %>
	</div>
</body>
<div class="container">
	<footer class="footer center">
	&copy;2015 215Labs <i class="fa fa-flask"></i>
	</footer>
</div>
</html>